In [1]:
###########################################################################################
#                                  Name:Bhushan Joshi                                     #
#                                  Enrollment:2162270307050                               #
#                                  Div:G                                                  #
#                                  Government Polytechnic Porbandar                       #
###########################################################################################

#Practical 4: Write a NumPy program to implement following operation


In [2]:
#Practical 4.1:to add, subtract, multiply, divide arguments element-wise
import numpy as np
arr = np.array([1, 2, 3])
arr1 = np.array([4, 5, 6])

print("Array 1:")
print(arr)

print("\nArray 2:")
print(arr1)
sum = np.add(arr, arr1)
subtract = np.subtract(arr, arr1) 
multiply = np.multiply(arr, arr1) 
divide = np.divide(arr, arr1) 
print("\nAddition:")
print(sum)
print("\nSubtraction:")
print(subtract)
print("\nMultiplication:")
print(multiply)
print("\nDivision:")
print(divide)

Array 1:
[1 2 3]

Array 2:
[4 5 6]

Addition:
[5 7 9]

Subtraction:
[-3 -3 -3]

Multiplication:
[ 4 10 18]

Division:
[0.25 0.4  0.5 ]


In [3]:
#Practical 4.2: to round elements of the array to the nearest integer
import numpy as np
arr1=np.array([1.2,2.3,3.4,4,5]).round()
print(arr1)

[1. 2. 3. 4. 5.]


In [4]:
#Practical 4.3 to calculate mean across dimension, in a 2D numpy array
import numpy as np
arr1=np.array([[1,2],[3,4],[5,6]])
print("Original Array is:",arr1)
arr2=np.mean(arr1,axis=0)
print("Mean along rows (axis 0):",arr2)
arr3=np.mean(arr1,axis=1)
print("Mean Along Columns (Axis 1):",arr3)


Original Array is: [[1 2]
 [3 4]
 [5 6]]
Mean along rows (axis 0): [3. 4.]
Mean Along Columns (Axis 1): [1.5 3.5 5.5]


In [5]:
#Practical 4.4 to calculate the difference between neighboring elements, elementwise of a given array
import numpy as np
arr = np.array([1, 3, 5, 7, 9])
print(arr)
diff = np.diff(arr)
print(diff)

[1 3 5 7 9]
[2 2 2 2]
